### ISSUE TITLE
Make it so you can adjust ssh port

### ISSUE THREAD

**Issue by victorpyra** [RedxAx/Remotely#3]
Currently its only possible to connect to ssh via port 22. 
However, if you have changed your ssh port, the whole purpose of the terminal becomes useless and you can't do anything.

It would be awesome, if you could change the port using params in the prompt: `ssh user@host -p [port]`
https://github.com/RedxAx/Remotely/blob/master/src/main/java/redxax/oxy/SSHManager.java#L56

Also it would be great, if you could make it happen, that you could paste your password with right click as it is known from other ssh-clients, as I haven't got it to work so far. 

Another thing that would be awesome is if you could use SSH keys to connect to a server. For example: 
**Add identity:** - You could manage your identities, create new identities, remove them and link user "bob" with an ssh key. 
`You could make this possible by using Jsch's identity system`.

Otherwise, really cool software so far and nice to play with! :)

**Comment by RedxAx** [comment]
Hey @victorpyra !
I didn't thought of making a custom port because I never used any other port in the alpha dev stage, I will update it to support it easily!

Pasting passwords too, noted.

But Identites, I was thinking to add that already and generate a public ash key but forgot about it. I will add everything in the next update!

Also, I'm working on a huge part of the mod that I showcased on the discord, please join us! You will see the master piece that I'm cooking!
https://discord.gg/UAEV8WgC6M

**Comment by RedxAx** [comment]
oh yeah, I made these changes like 5 days ago? Watch out for the next update!
